language: c++
sudo: required
compiler:
 - gcc

before_install:
 - cd scripts
 - ./install-qt 5.7.0
 - export CMAKE_PREFIX_PATH=/home/travis/build/davidcorbin/mygcc-application/scripts/Qt/5.7/gcc_64/bin
 - cd ..

script: 
 - python scripts/cpplint.py --headers=hpp src/*.cpp src/*/*.cpp include/*.hpp include/*/*.hpp
 - git submodule update --init --recursive
 - mkdir build
 - cd build
 - cmake ..
 - make

notifications:
  slack: grovecitycollege:Tg5JFkWtWXdNqGEDZQnxfv9S
