language: c++
sudo: required
compiler:
 - gcc

before_install:
 - cd scripts
 - ./install-qt 5.9.4
 - echo $CMAKE_PREFIX_PATH
 - cd ..

script: 
 - python scripts/cpplint.py --headers=hpp src/*.cpp src/*/*.cpp include/*.hpp include/*/*.hpp
 - git submodule update --init --recursive
 - mkdir build
 - cd build
 - cmake ..
 - make

notifications:
  slack: grovecitycollege:Tg5JFkWtWXdNqGEDZQnxfv9S
