language: c++
sudo: required
script: 
 - python scripts/cpplint.py --headers=hpp src/*.cpp src/*/*.cpp include/*.hpp include/*/*.hpp
 - ./scripts/build_ubuntu.sh

notifications:
  slack: grovecitycollege:Tg5JFkWtWXdNqGEDZQnxfv9S

git:
  submodules: false
